version: "3.7"

services:

    service_1:
        build: ./Service_1
        container_name: service_1
        image: markr1966/f1_service_1
        ports:
            - "5000:5000"
        networks:
            - f1_network

    service_2:
        build: ./Service_2
        container_name: service_2
        image: markr1966/f1_service_2
        networks:
            - f1_network

    service_3:
        build: ./Service_3
        container_name: service_3
        image: markr1966/f1_service_3
        networks:
            - f1_network

    service_4:
        build: ./Service_4
        container_name: service_4
        image: markr1966/f1_service_4
        networks:
            - f1_network

networks:
    f1_network:
        driver: bridge
        name: f1_network
    