---
    - hosts: 127.0.0.1
      connection: local
      become: true
      tasks:
      - name: Install NGINX
        apt:
          name: nginx
          state: latest
      - name: Start NGINX Service
        service:
          name: nginx
          state: started