---
- name: Install Docker dependencies
    apt:
      name: "{{ item }}"
      state: latest
      update_cache: yes
    with items:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    tags: docker
      
- name: Get DOcker GPG key
    apt_key:
      url: https://https://download.docker.com/linux/ubuntu/gpg
      state: present
    tags: docker

- name: Add docker packages to local repository  
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
      state: present
    tags: docker

- name: Install Docker
    apt:
      name: docker-ce
      state: latest
      update_cache: yes
    tags: docker
      
- name: Start docker
    service:
      name: docker
      state: started
        
- name: Add user to docker group
    shell: usermod -aG docker a
    tags: docker    

      
      
        

