- name: Check swarm status
  shell: docker node ls
  ignore_errors: true
  register: swarm_status
  tags: swarm

- name: Initialise Docker swarm
  shell: docker swarm init
  when: swarm_status.rc != 0
  run_once: true
  tags: swarm
  
- name: Manager host name
  shell: hostname
  register: manager_hostname
  tags: swarm

- name: Get worker node-join token
  shell: docker swarm join-token --quiet worker
  register: worker_token
  tags: swarm
  
- name: Output worker token
  add_host:
    name: "token"
    value: "{{ worker_token.stdout }}"

- name: Output Manager Hostname
  add_host:
    name: "manager_hostname"
    value: "{{ manager_hostname.stdout }}"
    
- name: Add worker to manager node
  shell: echo {{ hostvars['token']['value']}}    